// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE1ErwS5WEne2x1ICweZugtebTd7-muOk',
    appId: '1:1035220184984:web:a937888a29788bc0b545ed',
    messagingSenderId: '1035220184984',
    projectId: 'flutterauthen-8a274',
    authDomain: 'flutterauthen-8a274.firebaseapp.com',
    storageBucket: 'flutterauthen-8a274.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJivUqaByb8dtGsomAhoG_qyvWys0xgRY',
    appId: '1:1035220184984:android:119f4629eb1b0f22b545ed',
    messagingSenderId: '1035220184984',
    projectId: 'flutterauthen-8a274',
    storageBucket: 'flutterauthen-8a274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB7gAJgYa3qYwsDm_cDwmFTM8Wea0pfy0',
    appId: '1:1035220184984:ios:2011d4327289d482b545ed',
    messagingSenderId: '1035220184984',
    projectId: 'flutterauthen-8a274',
    storageBucket: 'flutterauthen-8a274.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB7gAJgYa3qYwsDm_cDwmFTM8Wea0pfy0',
    appId: '1:1035220184984:ios:5782ed65c9ed51d2b545ed',
    messagingSenderId: '1035220184984',
    projectId: 'flutterauthen-8a274',
    storageBucket: 'flutterauthen-8a274.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
